# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookStore_MariaEugenia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "PromiseKit"
  pod 'SnapKit'
  pod 'SDWebImage'

  target 'BookStore_MariaEugeniaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookStore_MariaEugeniaUITests' do
    # Pods for testing
  end

end
